### ISSUE TITLE
The Linke turbidity lookup table requires tables.

### ISSUE THREAD

**Issue by Roamer423** [pvlib/pvlib-python#1001]
**Describe the bug**
Hi, I used pvlib library for over 4 months and today when I wanted to run the code, it starts giving me the below error:

  File "C:\ProgramData\Anaconda3\lib\site-packages\pvlib\clearsky.py", line 188, in lookup_linke_turbidity
    import tables

  File "C:\Users\Navid Shirzadi\AppData\Roaming\Python\Python37\site-packages\tables\__init__.py", line 99, in <module>
    from .utilsextension import (

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\Concordia\PhD Thesis\Model\Optimization Model\Solar Modeling in Python\Solar_Modelling.py", line 56, in <module>
    tl = pvlib.clearsky.lookup_linke_turbidity(times, latitude, longitude)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pvlib\clearsky.py", line 190, in lookup_linke_turbidity
    raise ImportError('The Linke turbidity lookup table requires tables. '

**ImportError: The Linke turbidity lookup table requires tables. You can still use clearsky.ineichen if you supply your own turbidities.**

I installed pytables and scipy and all other required packages several time via conda and also pip but still getting the same error! I even uninstalled the whole anaconda navigator and installed it again and installed the pvlib and required packages via conda again but still receiving the same error. Please kindly advise.

**Comment by mikofski** [comment]
Sorry you are having this issue. What version of pvlib are you using? I cannot reproduce this with pvlib-0.7.1 from PyPI and with [pytables installed from the default Anaconda channel](https://anaconda.org/anaconda/pytables). Expand the details below to see what I mean:

<details>

```python
>>> import pvlib
>>> import pandas as pd

>>> t = pd.DatetimeIndex(pd.date_range(
...     start='1990-01-01 00:00:00',
...     end='1990-12-31 23:59:59',
...     tz='Etc/GMT+8',
...     freq='H'))
DatetimeIndex(['1990-01-01 00:00:00-08:00', '1990-01-01 01:00:00-08:00',
               '1990-01-01 02:00:00-08:00', '1990-01-01 03:00:00-08:00',
               '1990-01-01 04:00:00-08:00', '1990-01-01 05:00:00-08:00',
               '1990-01-01 06:00:00-08:00', '1990-01-01 07:00:00-08:00',
               '1990-01-01 08:00:00-08:00', '1990-01-01 09:00:00-08:00',
               ...
               '1990-12-31 14:00:00-08:00', '1990-12-31 15:00:00-08:00',
               '1990-12-31 16:00:00-08:00', '1990-12-31 17:00:00-08:00',
               '1990-12-31 18:00:00-08:00', '1990-12-31 19:00:00-08:00',
               '1990-12-31 20:00:00-08:00', '1990-12-31 21:00:00-08:00',
               '1990-12-31 22:00:00-08:00', '1990-12-31 23:00:00-08:00'],
              dtype='datetime64[ns, Etc/GMT+8]', length=8760, freq='H')

>>> tl = pvlib.clearsky.lookup_linke_turbidity(t, 37, -121)
1990-01-01 00:00:00-08:00    3.309677
1990-01-01 01:00:00-08:00    3.309677
1990-01-01 02:00:00-08:00    3.309677
1990-01-01 03:00:00-08:00    3.309677
1990-01-01 04:00:00-08:00    3.309677
                               ...
1990-12-31 19:00:00-08:00    3.300000
1990-12-31 20:00:00-08:00    3.300000
1990-12-31 21:00:00-08:00    3.300000
1990-12-31 22:00:00-08:00    3.300000
1990-12-31 23:00:00-08:00    3.300000
Freq: H, Length: 8760, dtype: float64

>>> pvlib.__version__
'0.7.1'
```

</details><br/>

I'm pretty sure I know what's happening here. In your post above you show the path to tables as `AppData\Roaming\Python\Python37\site-packages\tables_init_.py` which is troubling because if you're using conda with pip, then your site-packages should be installed in your conda environment which you also show above as `C:\ProgramData\Anaconda3\` which is also troubling because this should be `AppData\Local\Continuum\Anaconda3\`.

So you seem to have 2 problems, but the main problem is a `$PATH` and `$PYTHONPATH` clash caused by having 2 Pythons installed.

1. Your Anaconda is installed system-wide instead of in your local profile. IMO this can be sub-optimal b/c if you don't have admin rights then you can't create environments using only `-n name` instead you have to use `-p PATH` which is less convenient.
    * Did you install Anaconda using admin rights? Do you have admin rights to your computer? Did someone else install Anaconda on your computer for you?

2. You may have another Python interpreter on your computer, perhaps installed in `C:\Program Files\Python37` which has installed packages from PyPI using the [`--user` mode](https://packaging.python.org/tutorials/installing-packages/#installing-to-the-user-site). It's okay to have more than one Python on your computer, but it means that you need to manage packages more carefully to avoid `$PATH` & `$PYTHONPATH` clashes.
    * Do you have another non-Anaconda Python interpreter installed on your computer? Perhaps from https://python.org/downloads? Or perhaps you installed it via some other application like Visual Studio? Perhaps someone else installed another Python on your computer? Are you using this other Python?

I'm not sure the best way to fix your system without knowing more about it and how you plan to use it. And I don't think there's really any easy way to fix it.

1. One temporary fix that might work would be to create a new conda environment using [`-p PATH`](https://docs.conda.io/projects/conda/en/latest/commands/create.html):

```bash
(base) $ mkdir -p ~/my-conda-envs
(base) $ conda create -p ~/my-conda-envs/pvlib-env
(base) $ conda activate ~/my-conda-envs/pvlib-env
(~/my-conda-envs/pvlib-env) $ conda config --env ~/my-conda-envs/pvlib-env --add channels conda-forge
(~/my-conda-envs/pvlib-env) $ conda install pvlib-python
```

You can see the disadvantage of having to use the `-p PATH` option with conda because instead of using a name, you have to provide `PATH` every time.

2. Another way to fix this would be if you really do have another Python installed on your computer, just use it instead of Anaconda. Assuming this Python isn't on your system `$PATH` already then you will need to use the full path to and execute pip with the `-m` option:

```bash
$ /c/Program\ Files/Python37/python.exe -m pip install --user pvlib[all]
```

**Although I must admit that I _really_ don't recommend doing this!** In fact I would recommend that whether you're using conda or pip, you should always use a virtual environment, which would avoid most of these `$PATH` & `$PYTHONPATH` clashes all together

3. Ultimately I think you should do the following:

    * Uninstall your system-wide installation of Anaconda and reinstall it or preferably [miniconda](https://docs.conda.io/en/latest/miniconda.html) into your user profile without admin rights. Then you can use the `-n NAME` option to create and activate conda environments
    * Delete this folder: `AppData\Roaming\Python\Python37\` and don't install anything using your other non-Anaconda Python without creating a virtual environment using [the builtin Python venv module](https://docs.python.org/3.7/library/venv.html).
    * As much as possible don't mix PyPI and conda, or even conda channels. If you think you will need conda-forge, add it to your conda channels list first before defaults

This can be fixed, but it will take a little work and some iterations possibly. Good luck
