### ISSUE TITLE
[Question] How to use horizontal tracking and vertical tracking parameters? 

### ISSUE THREAD

**Issue by pratapagiri** [pvlib/pvlib-python#1200]
Is there a way to user horizontal tracking and vertical tracking parameters (these values set to true or false) with the SingleAxisTracker ?

**Comment by cwhanse** [comment]
I'm sorry, I don't understand your question. Could you elaborate on the system you wish to model?

This appears to be a question about how to use pvlib rather than a request for a feature or reporting a bug. Could you post the question to the [pvlib google group](https://groups.google.com/forum/#!forum/pvlib-python)?

Cheers,

Cliff
