### ISSUE TITLE
"latest" docs don't make it clear that they contain unreleased features

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1260]
**Is your feature request related to a problem? Please describe.**
Someone on stackoverflow tried using the example code in our `latest` docs with pvlib 0.8.1 because they didn't realize the feature wasn't in a stable release yet:  https://stackoverflow.com/questions/68357949/cant-find-pvlib-pvsystem-array

**Describe the solution you'd like**
A warning banner at the top of the pages at `https://pvlib-python.readthedocs.io/en/latest/` saying something like "this page might use unreleased features; click here to view documentation for the current pvlib release".  One straightforward method described [here](https://michaelgoerz.net/notes/showing-a-warning-for-the-latest-documentation-on-readthedocs.html) looks like this:

![image](https://user-images.githubusercontent.com/57452607/125537238-3c63e415-1c24-47b7-b749-c7b5c3739362.png)

**Describe alternatives you've considered**
- Maybe just disable the "latest" docs altogether?  If it's for unreleased features then what's the value in making it public?
- Another option, not sure it's maintained though: https://github.com/humitos/sphinx-version-warning

**Comment by AdamRJensen** [comment]
Recently, I have been finding myself often referring to new functions in the latest release, e.g., sending links to people. So I definitely think it has some usage. It's nice being able to somewhere seeing the current GitHub version, which I guess what 'latest' is.

As long as it defaults to 'stable', then I don't see an issue also having 'latest'. Clearly, whomever posted the question must have been peeking around the documentation in order to find the 'latest'.

I'm +1 for the banner solution!

**Comment by wholmgren** [comment]
+1 for the banner, but after 0.9.
