### ISSUE TITLE
LGTM has 6 errors 

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#1275]
**Describe the bug**
LGTM shows 6 errors,  at least one seems easy to fix there is a self alignment that seems redundant

**To Reproduce**
https://lgtm.com/projects/g/pvlib/pvlib-python/alerts/?mode=list&severity=error

**Expected behavior**
No errors?

**Screenshots**
https://lgtm.com/projects/g/pvlib/pvlib-python/alerts/?mode=list&severity=error

**Versions:**
 - ``pvlib.__version__``: 0.9ish
 - ``pandas.__version__``: ?
 - python: 3

**Additional context**
https://lgtm.com/projects/g/pvlib/pvlib-python/alerts/?mode=list&severity=error

**Comment by wholmgren** [comment]
Certainly should fix that self assignment. Maybe silence the others?

**Comment by mikofski** [comment]
I found a Python "LGTM alert suppression" example here: https://lgtm.com/help/lgtm/alert-suppression#python

**Comment by wholmgren** [comment]
I've clicked the Hide button on a handful of similar alerts in the past. I didn't know about the comment option until now.

<img width="1342" alt="Screen Shot 2021-08-09 at 9 27 53 AM" src="https://user-images.githubusercontent.com/4383303/128740806-da5936a9-56f7-4bb2-be13-31dc44641a76.png">

I tried looking into it a few years ago and didn't figure it out. Maybe someone smarter than me can figure it out.

**Comment by chrisorner** [comment]
> I've clicked the Hide button on a handful of similar alerts in the past. I didn't know about the comment option until now.
> 
> <img alt="Screen Shot 2021-08-09 at 9 27 53 AM" width="1342" src="https://user-images.githubusercontent.com/4383303/128740806-da5936a9-56f7-4bb2-be13-31dc44641a76.png">
> 
> I tried looking into it a few years ago and didn't figure it out. Maybe someone smarter than me can figure it out.

This is a [bug](https://github.com/github/codeql/issues/2015#issue-497774539) in LGTM. It raises this error because of the user function test in test_modelchain.py: 
![image](https://user-images.githubusercontent.com/36364446/192496956-9fad2d68-7159-46c4-b080-7a9be0814af0.png)

Where `constant_aoi_loss` is a Python partial function which is the known bug in LGTM. So this error can be ignored. I am going to take a look at the others as well.

**Comment by chrisorner** [comment]
I am pretty sure that the alerts under non-callable can be ignored as well:
![image](https://user-images.githubusercontent.com/36364446/192514552-29501d96-4689-4e29-88eb-e71f12eeda60.png)

I described the issue [here](https://github.com/github/codeql/issues/10587) because I think it's also a bug in LGTM.
