### ISSUE TITLE
```get_pvgis_tmy``` results don't match PVGIS website 

### ISSUE THREAD

**Issue by UGuntupalli** [pvlib/pvlib-python#1360]
**Describe the bug**
Data retrieved using pvlib does not match data in pvgis website 

**To Reproduce**
```python
import pvlib 
from pvlib.iotools import get_pvgis_tmy 


# Print version to confirm it is the latest 
print(pvlib.__version__)  # confirms it is 0.9.0 

# Define two coordinates (1 each in US and EU) 
latitude_us, longitude_us = 33.21, -95.72
latitude_eu, longitude_eu = 37.66, 13.76

# Pull TMY data for both locations 
us_pvgis_tmy, _, _, _ = get_pvgis_tmy(latitude_us, longitude_us)
eu_pvgis_tmy, _, _, _ = get_pvgis_tmy(latitude_eu, longitude_eu)

# Calculate annual GHI 
print(f''' Annual GHI at US Test site is: {us_pvgis_tmy['G(h)'].sum()/1000}''')
print(f''' Annual GHI at EU Test site is: {eu_pvgis_tmy['G(h)'].sum()/1000}''')
```

**Expected behavior**
Data download using pvlib iotools should match the original source i.e. Pvgis 

**Screenshots**

![image](https://user-images.githubusercontent.com/47903157/147472128-03662139-3f9e-4dc3-947f-a651be4190f3.png)

**Versions:**
 - ``pvlib.__version__``:  0.9.0
 - ``pandas.__version__``: 1.2.4 
 - python: 3.8.0 

**Additional context**
Using the Pvgis built-in TMY tool (https://re.jrc.ec.europa.eu/pvg_tools/en/#TMY), the following files were downloaded from PVGIS website for the test sites used in the above code sample. None of these match against the data that is retrieved by the code. Can you kindly help explain the delta ? 

[tmy_33.210_-95.720_2006_2015.csv](https://github.com/pvlib/pvlib-python/files/7780158/tmy_33.210_-95.720_2006_2015.csv)
[tmy_37.660_13.760_2006_2015.csv](https://github.com/pvlib/pvlib-python/files/7780161/tmy_37.660_13.760_2006_2015.csv)
[tmy_33.210_-95.720_2005_2014.csv](https://github.com/pvlib/pvlib-python/files/7780162/tmy_33.210_-95.720_2005_2014.csv)
[tmy_37.660_13.760_2005_2014.csv](https://github.com/pvlib/pvlib-python/files/7780163/tmy_37.660_13.760_2005_2014.csv)
[tmy_37.660_13.760_2007_2016.csv](https://github.com/pvlib/pvlib-python/files/7780165/tmy_37.660_13.760_2007_2016.csv)

**Comment by AdamRJensen** [comment]
The reason that they differ is that the PVGIS website uses 10 year period for calculating the TMY, whereas the API defaults to using all years. This results in different months being used in the final TMY dataset.

From the [PVGIS API documentation](https://ec.europa.eu/jrc/en/PVGIS/docs/noninteractive):
![image](https://user-images.githubusercontent.com/39184289/147474624-1445a3bd-0082-43fa-ba6d-de23c3fcebe6.png)

The information is also included in the documentation of the pvlib function [get_pvgis_tmy](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.iotools.get_pvgis_tmy.html).

In order to obtain the same results as the website, it is necessary to specify `startyear` and `endyear`. E.g., for the first file you listed (tmy_33.210_-95.720_2006_2015.csv), the correct request would look like this:

    data, months_selected, inputs, meta = get_pvgis_tmy(33.21, -95.722, startyear=2006, endyear=2015)

Note that the specific months used in the TMY are given in the `months_selected` variable shown above. If you compare this variable with and without the `startyear`/`endyear` arguments you will see that the months used change.

**Comment by UGuntupalli** [comment]
@AdamRJensen, 

Thank you for the clarification. PVsyst also offers a way to pull the PVGIS data (https://www.pvsyst.com/help/meteo_source_pvgis.htm). However, what is not clear at least reading this documentation is whether PVsyst is querying hourly data or monthly data. 

Is there a comparable form of getting the equivalent data as imported via Pvsyst using Pvlib ?

**Comment by kanderso-nrel** [comment]
Hi @UGuntupalli, without knowing what exactly PVsyst is doing, I'm not sure we can advise how to replicate it in python.  Maybe someone else knows more about that PVsyst function.  That docs page you linked seems to say that it is no longer available in PVsyst anyway.
