### ISSUE TITLE
pv loss due to temperature 

### ISSUE THREAD

**Issue by 115522** [pvlib/pvlib-python#1610]
hello Everyone , I am new at pvlib and I want know how can I calculate PV loss due to temperature with pvlib I only found how to calculate cell temperature , any maths formula will be appriciated 

amany thanks in advance

**Comment by kanderso-nrel** [comment]
Hi @115522, thanks for your interest in pvlib.  We use these github issues for project development, and to make that easier for us we ask that non-development usage questions like this one and #1607 be asked in other places:

- https://groups.google.com/g/pvlib-python
- https://github.com/pvlib/pvlib-python/discussions

Can you post your questions to one of those forums instead of as github issues?  Thank you!
