### ISSUE TITLE
Please update the PVGIS5 to PVGIS5.2

### ISSUE THREAD

**Issue by Dawe890311** [pvlib/pvlib-python#1635]
The [iotools.get_pvgis_tmy] is old, so when you use it analysis some location, such as Peking and Shanghai, you will raise a error(HTTPError: Location out of the spatial coverage of PVGIS5), but the PVGIS5.2 have put these location into their database, so please update, thank you!

**Comment by AdamRJensen** [comment]
Hi @Dawe890311 

By default the pvlib ``get_pvgis_tmy`` function uses the base endpoint: https://re.jrc.ec.europa.eu/api/

PVGIS has yet to redirect this endpoint to the new version of the database (5.2). See previous discussions here: #1415.

In order to use the new version 5.2, the specific URL for version 5.2 needs to be specified:

    import pvlib
    
    data, months_selected, inputs, meta = pvlib.iotools.get_pvgis_tmy(
        latitude=28.965734,
        longitude=117.147418,
        url='https://re.jrc.ec.europa.eu/api/v5_2/',
    )
