### ISSUE TITLE
scipy.misc.derivative is deprecated

### ISSUE THREAD

**Issue by kanderso-nrel** [pvlib/pvlib-python#1644]
scipy [v1.10.0](https://docs.scipy.org/doc/scipy/release.1.10.0.html#deprecated-features) (released Jan 3, 2023) has deprecated `scipy.misc.derivative`, a function used by `pvlib.ivtools.sdm.pvsyst_temperature_coeff`.  The deprecation notice mentions some alternatives (although I'm not confident a new dependency is warranted in our case):

> pvlib/ivtools/sdm.py:1347: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools

Noticed in this CI run: https://github.com/pvlib/pvlib-python/actions/runs/3992734328/jobs/6848836375#step:9:130

**Comment by cwhanse** [comment]
I noticed that too, in other work. scipy is not going to provide any numeric differentiation tools. If we keep the pvsyst_temperature_coeff function (I vote yes), and are considering a new dependency, I vote against either autograd or its successor, JAX; they are awkward since they wrap numpy. My preference would be to code our own calculation using a finite difference formula.

**Comment by mikofski** [comment]
Maybe check [statsmodels](https://www.statsmodels.org/stable/index.html) I seem to recall that it has a simple derivative function, but I can't find it quickly now so maybe I was mistaken?

**Comment by adriesse** [comment]
+1 for explicit finite difference calculation
