### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by langestefan** [pvlib/pvlib-python#1721]
**Describe the bug**
Broken links in PVlib docs. 

**To Reproduce**
1. Go to [pvsystem_tutport](https://pvlib-python-dacoex.readthedocs.io/en/pvsystem_tutport/usage.html), or [pvlib tutorials](https://nbviewer.ipython.org/github/pvlib/pvlib-python/tree/main/docs/tutorials/)
2. On tutport all the examples get a 404, nbviewer doesn't load either

**Comment by kandersolar** [comment]
Thanks @langestefan!  The first one is a six-year-old unofficial fork of the pvlib documentation (see how the url is `pvlib-python-dacoex.readthedocs` instead of just `pvlib-python.readthedocs`).  We can't fix that one since it's not our webpage.  

We can fix the second one though.  Looks like `docs/sphinx/source/index.rst` has two instances of the outdated `nbviewer.ipython.org` that need to be updated.

**Comment by langestefan** [comment]
@kandersolar I see, thanks. Not sure how I found that first link, I think it was somewhere at the top of google search results? Anyway good to know it's outdated, I will refer to the second link in the future. You can close the issue now if you want

**Comment by kandersolar** [comment]
Let's keep it open until our outdated nbviewer links are fixed :)

Fixing those would be an easy first PR if anyone is interested.

**Comment by kshitiz305** [comment]
Hi @kandersolar I would like to work on this could you help me with the link that needs to be updated.

**Comment by kandersolar** [comment]
Hello @kshitiz305, the links in question are in this file: https://github.com/pvlib/pvlib-python/blob/main/docs/sphinx/source/index.rst?plain=1

There are two URLs for `nbviewer.ipython.org/...`.  I think they just need to be updated to `nbviewer.org/...`.
