### ISSUE TITLE
problems with pvlib.erbs for calculating dni

### ISSUE THREAD

**Issue by AugustVan** [pvlib/pvlib-python#2092]
Hello,
For a project that I'm currently working on I have to calculate the dhi an dni with the ghi values I measured with a sensor. For this I used PVlib.erbs  and pvlib.solarposition (for calculating the zenith angles throughout the day). The problem now is that the calculated values of dni are sometimes really large as shown in the picture below while the ghi I measured isn't perticullarly big. I don't know what I did wrong to get these large values for dni and how I can fix this. The consequence of these large dni values is that they cause an error in a simulation model I made to use the ghi, dni and dhi values. 
![image](https://github.com/pvlib/pvlib-python/assets/152192430/ade08ed2-4429-4fb5-bec4-ed3716fb37d8)

[GHI-data.xlsx](https://github.com/user-attachments/files/15864876/GHI-data.xlsx). In the file GHI-data you can see all the results of the program I wrote. As you can see in the file, these high dni values keep coming back for specific hours. Is there anyone that knows what I did wrong in the code or is this something I can't fix?
The code I used for this can be seen below. 
![image](https://github.com/pvlib/pvlib-python/assets/152192430/ff5879bc-d60e-40a1-b6e7-f24de7b19899)
Kind regards

August

**Comment by AdamRJensen** [comment]
DNI stands for direct normal irradiance, meaning it is measured normal to the sun, whereas GHI and DHI are measured on a horizontal surface. GHI can be calculated from DHI and DNI as such:

    GHI = DHI + DNI * cos (zenith)

thus it is perfectly fine for DNI to be much higher than GHI when the solar zenith angle is high (low sun elevation).

**Comment by kandersolar** [comment]
> it is perfectly fine for DNI to be much higher than GHI when the solar zenith angle is high (low sun elevation).

This is true, but DNI of 2000+ W/m2 at as high a sun position as 79 degrees zenith seems too large to be due to the "normal" cosine blowup.

@AugustVan do the high values only appear near one of dawn and dusk, i.e. is there an asymmetry across the day?  If so, there may be a mismatch between your calculated solar position values and your irradiance data.  `get_solarposition` returns the solar position for the exact timestamp you pass (e.g. solar position for the `07:00` timestamp is for specifically `07:00`), whereas hourly irradiance data often reflect the average over the hour before or after the timestamp (e.g. the value for `07:00` is the average over `07:00-07:59`).  If that's the case for your data, then you're using solar positions that don't quite correspond to the measurements, so large errors would be expected when small differences in solar position get amplified near dawn or dusk as @AdamRJensen points out.

These links may be helpful: 
- https://pvlib-python.readthedocs.io/en/stable/user_guide/faq.html#why-don-t-my-simulation-results-make-sense
- https://pvlib-python.readthedocs.io/en/stable/gallery/irradiance-transposition/plot_interval_transposition_error.html
