### ISSUE TITLE
netCDF4 missing in dependencies

### ISSUE THREAD

**Issue by emulbreh** [pvlib/pvlib-python#231]
netCDF4 is imported unconditionally in the forecast module but isn't included in setup.py. 
https://github.com/pvlib/pvlib-python/blob/master/pvlib/forecast.py#L6

This breaks the documentation build: http://pvlib-python.readthedocs.io/en/latest/forecasts.html

**Comment by wholmgren** [comment]
See this comment regarding the documentation on readthedocs: https://github.com/pvlib/pvlib-python/pull/180#issuecomment-235935887 I'm sure it will work on rtd eventually.

I don't want to add netCDF4 to the required dependencies because only a fraction of pvlib users will need it and it's a non-trivial installation.
