### ISSUE TITLE
`pvlib.ivtools.sdm.fit_desoto_sandia` has incorrect sign for returned `dEgdT`

### ISSUE THREAD

**Issue by kandersolar** [pvlib/pvlib-python#2321]
`fit_desoto_sandia` incorrectly returns `+0.0002677` instead of `-0.0002677` for `dEgdT`:

https://github.com/pvlib/pvlib-python/blob/891778cc9ceb11e159991d08a6d6cb2d09661bdf/pvlib/ivtools/sdm.py#L874-L886

That value is used both for the returned value and in the equations that compute other SDM parameters.  I've not inspected the math to see whether the sign should be fixed in both places, or only for the returned value.

Noticed in #2315.

**Comment by cwhanse** [comment]
The bug stems from a laziness in the original report, where I dropped a pair of parathenses. The Matlab code was transcribed from a printed equation, and the pvlib code was transcribed from Matlab.


The default value from De Soto et al. paper is `dEgdT=-0.0002577`, and the relevant equation in the De Soto model is

```
E_g = EgRef * (1 + dEgdT*(Tcell_K - Tref_K))
```

The code in `fit_desoto_sandia` could have been rendered

```
 dEgdT = -0.0002677 
 x_for_io = const['q'] / const['k'] * ( 
     1. / tok - (1. / tck[u] + dEgdT * (tc[u] - const['T0']) / tck[u]))
```
 
I think this should be the fix, rather than adding a minus sign to the later line of code.

**Comment by echedey-ls** [comment]
May I tackle this issue?

**Comment by cwhanse** [comment]
@echedey-ls please do. LMK if you run into issues with tests, I can help with the known solutions.

**Comment by echedey-ls** [comment]
> The default value from De Soto et al. paper is `dEgdT=-0.0002577`

@cwhanse , just in case, that 5 is a typo, right? It should be 0.0002677.

**Comment by cwhanse** [comment]
> > The default value from De Soto et al. paper is `dEgdT=-0.0002577`
> 
> @cwhanse , just in case, that 5 is a typo, right? It should be 0.0002677.

That is correct.
