### ISSUE TITLE
Tutorial: pvsystem.ipynb

### ISSUE THREAD

**Issue by cdeline** [pvlib/pvlib-python#267]
I'm getting some errors when running pvsystem.ipynb in the PVLib tutorials directory.  Specifically code block 17 should be replaced with 
`pacs = pvsystem.snlinverter(vdcs, pdcs, inverters['ABB__MICRO_0_25_I_OUTD_US_208_208V__CEC_2014_'])`

Also, code block 22 is throwing an error at `irrad_data = clearsky.ineichen(times_loc, tus.latitude, tus.longitude)`.  It looks like this code example is passing local datetime into clearsky.ineichen, rather than apparent_zenith angle in degrees.

I'm using the latest pvlib 0.4.1 python 2.7.

Chris Deline

**Comment by wholmgren** [comment]
Thanks for pointing that out and sorry for the confusion. We made some API changes in 0.4 and neglected to update many of the jupyter/ipython tutorials. The online documentation should be up to date: http://pvlib-python.readthedocs.io 

Your second error can be fixed with: ``irrad_data = tus.get_clearsky(times_loc)``

**Comment by wholmgren** [comment]
This one should work better:

http://nbviewer.jupyter.org/github/wholmgren/pvlib-python/blob/tutorials041/docs/tutorials/pvsystem.ipynb

I'll add this to a future release.

**Comment by cdeline** [comment]
Thanks guys!

Chris Deline
National Renewable Energy Laboratory
303-384-6359
