### ISSUE TITLE
pvwatts_dc in PVSystem

### ISSUE THREAD

**Issue by cedricleroy** [pvlib/pvlib-python#319]
I am just wondering how ```pvwatts_dc``` method is intended to be used. Looking at the test, it sounds like we have to create a custom ```module_parameters``` with ```pdc0``` and ```gamma_pdc```. Those two parameters are not present in the standards module objects retrieved from CECMod or SandiaMod. 
```pdc0``` looks like being more a parameter tied to a group of modules rather than a module alone. Could it be calculated from the standard ```module_parameters``` entered to the instance in combination with ```modules_per_string``` and ```strings_per_inverter```?. It would perhaps be more "system like", and we would have a use of the instance calculating ```pvwatts_dc```.

As well, there is no ```eta_inv_nom``` / ```eta_inv_ref``` in the ```inverter_parameters``` object retrieved from CECMod. Calculating ```pvwatts_ac``` is not going to work straight. Maybe it could be more explicit that it has to be manually inserted (raise a custom error if not present ?).

**Comment by wholmgren** [comment]
> Looking at the test, it sounds like we have to create a custom module_parameters with pdc0 and gamma_pdc. 

correct.

> Those two parameters are not present in the standards module objects retrieved from CECMod or SandiaMod.

correct, but you can convert. might be worthwhile to have a standard conversion function in library.

> pdc0 looks like being more a parameter tied to a group of modules rather than a module alone. Could it be calculated from the standard module_parameters entered to the instance in combination with modules_per_string and strings_per_inverter?. It would perhaps be more "system like", and we would have a use of the instance calculating pvwatts_dc.

For the use case you're describing, yes, that makes sense. Note that ``ModelChain`` can scale the dc calculations before passing it to the selected ac method. 

In general, see section 3 of http://pvwatts.nrel.gov/downloads/pvwattsv5.pdf

> As well, there is no eta_inv_nom / eta_inv_ref in the inverter_parameters object retrieved from CECMod. Calculating pvwatts_ac is not going to work straight.

These are optional parameters and I think it does work without them. I put in pr about a month ago that addressed the fact that inverter_parameters needed to be a dict instead of the default None value, though.

I'm sure we could better document all of this and I'd welcome your help to do so.
