### ISSUE TITLE
test_clearsky.test_simplified_solis_series_elevation is declared twice

### ISSUE THREAD

**Issue by KonstantinTr** [pvlib/pvlib-python#387]
We've got two declarations of test_clearsky.test_simplified_solis_series_elevation
![image](https://user-images.githubusercontent.com/16244350/31707129-00447b2c-b3f4-11e7-8504-5605485bd417.png)

During the testing we will run the one on the left:
![image](https://user-images.githubusercontent.com/16244350/31707087-e05f6614-b3f3-11e7-9220-ed87d87b8037.png)

What of these two test functions should we keep?

**Comment by cwhanse** [comment]
I much prefer the shorter function on the left, because it has no dependence on other functions, e.g., get_solarposition.

Do we agree that a single elevation angle (80) is sufficient? 

I think that using a keyword argument in the call to simplified_solis, e.g., apparent_elevation=pd.Series(80), would help make this more easily understood.

**Comment by wholmgren** [comment]
I'm guessing that I screwed up some copy/pasting when making these tests. 

I agree that the left is preferable. I think we want to ensure that the function returns 0s for elevation angles less than 0. A single additional value is probably good enough for that.

**Comment by wholmgren** [comment]
In reviewing #388 I realized that there is [another test](https://github.com/pvlib/pvlib-python/blob/39c0862a33c3b6286ef1458a036547ed6beec399/pvlib/test/test_clearsky.py#L290-L298) that explicitly tests that the function returns 0s for elevation angles less than 0, so I retract my previous comment.

**Comment by wholmgren** [comment]
closed by #388
