### ISSUE TITLE
Implement another snow loss model like Bill Marion as an alt to pvwatts

### ISSUE THREAD

**Issue by mikofski** [pvlib/pvlib-python#577]
I'll try to track down the papers on this

**Comment by anomam** [comment]
Hello folks, @mikofski @wholmgren @cwhanse 
My group would like to open-source in pvlib the snow model that Defne Gun presented at the 10th PVPMC workshop in 2018: see [link](https://pvpmc.sandia.gov/resources-and-events/events/2018-10th-pv-performance-modeling-workshop/) to workshop website and [link](https://pvpmc.sandia.gov/download/6446/) to presentation.
I also talked with Dan Riley (do you know his Github username? I would like to tag him) and it seems that it would be very useful for ongoing research to have that model implemented so that his group can build on top of it.
Would that be ok? Please let us know if there are any concerns.

**Comment by mikofski** [comment]
ICYMI @patrickjmathiesen

**Comment by mikofski** [comment]
I'd still like to see Bill Marion's model here,  but I think it would be great to see the SunPower model too,  thanks!

**Comment by DanRiley** [comment]
I think that Defne's additions are just on top of Bill's model, so I'm hopeful that by getting Defne's model that we would also get Bill's. I'll be working on getting both of them into MATLAB pv_lib.

**Comment by cwhanse** [comment]
Thanks for the initiative on this. Two questions to help identify where to put the code:
- Does the model modify irradiance or power?
- What system characteristics are needed beyond tilt and azimuth?  It appears that a length dimension and height above ground are needed.

**Comment by cwhanse** [comment]
@ryanblumie @kevinsa5 Ryan let's discuss your offer here

**Comment by mikofski** [comment]
FYI: DNV GL would also like to contribute the Townsend snow model, I have 3 references. The inputs are typically daily snowfall history, gcr, module lower edge height above ground, ambient temperature,  and the output is binary: no power direw to snow cover, or power. AFAIK there is no partial power. We already have the code ready.

**Comment by cwhanse** [comment]
@mikofski inputs are similar to Marion's model. As far as pvlib, we need to decide where to record the inputs and how to name them. Tossing one idea out:
`PVSystem.height_above_ground`
`PVSystem.gcr` - need to move from `SingleAxisTracker.gcr`
Daily snowfall doesn't fit nicely in `weather` due to the expected daily timesteps. Ideas for a nice way to host snowfall/rainfall other daily values (turbidity perhaps)?

**Comment by wholmgren** [comment]
> Daily snowfall doesn't fit nicely in weather due to the expected daily timesteps. Ideas for a nice way to host snowfall/rainfall other daily values (turbidity perhaps)?

Is this only a concern for integrating the snow loss model with `ModelChain.run_model(weather)` or do we need to address it when implementing the basic function?

**Comment by cwhanse** [comment]
The concern is for `ModelChain`  The basic function should expect to get the inputs that the model requires.
