### ISSUE TITLE
move linke turbidity lookup out of clearsky.ineichen 

### ISSUE THREAD

**Issue by wholmgren** [pvlib/pvlib-python#95]
I'd like to move the Linke turbidity look up code out of ``clearsky.ineichen`` and into its own function. The ``clearsky.ineichen`` API can remain the same, and it can call the new function to automatically pull in the turbidity data. Two advantages: you can easily access the turbidity data that is driving your pv models, you can cache the result so that you don't have to read and process the file over and over.

**Comment by cwhanse** [comment]
I agree. There are other data sources for turbidity and it would be useful to have the option to supply turbidity as input to the Ineichen (or other) models.

Cliff

Sent from my iPhone

On Nov 3, 2015, at 9:46 AM, Will Holmgren <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd like to move the Linke turbidity look up code out of clearsky.ineichen and into its own function. The clearsky.ineichen API can remain the same, and it can call the new function to automatically pull in the turbidity data. Two advantages: you can easily access the turbidity data that is driving your pv models, you can cache the result so that you don't have to read and process the file over and over.

-
